### ISSUE TITLE
Design the Website more thoroughly

### ISSUE THREAD

**Issue by SkyeTheDemon** [SkyeTheDemon/SkyeTheDemon.github.io#2]
work on the css/design
preferably w/ figma maybe?

**Comment by SkyeTheDemon** [comment]
also make sure to ask for opinions, after a few color palettes are picked out.
I want this to be my branding of sorts.
not sure what colors would fit best however.

**Comment by cysabi** [comment]
An example color palette that was taken off of Discord.
- - -
![image](https://user-images.githubusercontent.com/47790183/90189240-cf37fe00-dd8a-11ea-88b4-61c690a03873.png)
> *https://coolors.co/f1e8b8-f9e784-e58f65-d05353-802323-191919*

**Comment by SkyeTheDemon** [comment]
Website is going to be going through a full redesign as a final project for my web design class
